'use strict';
module.exports = [{
  email: 'admin@yopmail.com',
  password: 'password',
  verificationToken: null,
  emailVerified: true,
}, {
  email: 'jose@yopmail.com',
  password: 'password',
  firstName: 'jose',
  lastName: 'lucas',
  verificationToken: null,
  emailVerified: true,
}, {
  email: 'unverified@yopmail.com',
  password: 'password',
  firstName: 'no',
  lastName: 'name',
  verificationToken: null,
  emailVerified: false,
}, {
  email: 'jm@yopmail.com',
  password: 'password',
  firstName: 'jean michel',
  lastName: 'robin',
  verificationToken: null,
  emailVerified: true,
}, {
  email: 'roro@yopmail.com',
  password: 'password',
  firstName: 'roméo',
  lastName: 'leclercq',
  verificationToken: null,
  emailVerified: true,
}, {
  email: 'sam@yopmail.com',
  password: 'password',
  firstName: 'sam',
  lastName: 'caron',
  verificationToken: null,
  emailVerified: true,
}];
