'use strict';
module.exports = [{
  email: 'admin@yopmail.com',
  password: 'password',
  firstName: 'admin',
  lastName: 'admin',
  verificationToken: null,
  emailVerified: true,
  pictureProfile: 'https://randomuser.me/api/portraits/men/78.jpg',
  pictureProfileHeader: 'https://www.planwallpaper.com/static/images/blackmoon-wallpaper-background.jpg',
  pseudo: 'Tired Widow',
}, {
  email: 'jose@yopmail.com',
  password: 'password',
  firstName: 'jose',
  lastName: 'lucas',
  verificationToken: null,
  emailVerified: true,
  pictureProfile: 'https://randomuser.me/api/portraits/men/77.jpg',
  pictureProfileHeader: 'https://www.planwallpaper.com/static/images/2511289_GFurDeb.jpg',
  pseudo: 'Frozen Rose',
}, {
  email: 'unverified@yopmail.com',
  password: 'password',
  firstName: 'no',
  lastName: 'name',
  verificationToken: null,
  emailVerified: false,
}, {
  email: 'jm@yopmail.com',
  password: 'password',
  firstName: 'jean michel',
  lastName: 'robin',
  verificationToken: null,
  emailVerified: true,
  pictureProfile: 'https://randomuser.me/api/portraits/men/79.jpg',
  pictureProfileHeader: 'https://www.planwallpaper.com/static/images/background-wallpapers-33.jpg',
  pseudo: 'Hungry Grandma',
}, {
  email: 'roro@yopmail.com',
  password: 'password',
  firstName: 'roméo',
  lastName: 'leclercq',
  verificationToken: null,
  emailVerified: true,
  pictureProfile: 'https://randomuser.me/api/portraits/men/80.jpg',
  pictureProfileHeader: 'https://www.planwallpaper.com/static/images/FreeGreatPicture.com-18429-hd-color-background-wallpaper.jpg',
  pseudo: 'Major Geyser',
}, {
  email: 'sam@yopmail.com',
  password: 'password',
  firstName: 'sam',
  lastName: 'caron',
  verificationToken: null,
  emailVerified: true,
  pictureProfile: 'https://randomuser.me/api/portraits/women/28.jpg',
  pictureProfileHeader: 'https://www.planwallpaper.com/static/images/1968081.jpg',
  pseudo: 'Perfect Panther',

}];
