'use strict';
module.exports = [{
  email: 'admin@yopmail.com',
  password: 'password',
  verificationToken: null,
  emailVerified: true,
}, {
  email: 'jose@yopmail.com',
  password: 'password',
  verificationToken: null,
  emailVerified: true,
}, {
  email: 'unverified@yopmail.com',
  password: 'password',
  verificationToken: null,
  emailVerified: false,
}, {
  email: 'jm@yopmail.com',
  password: 'password',
  verificationToken: null,
  emailVerified: true,
}, {
  email: 'roro@yopmail.com',
  password: 'password',
  verificationToken: null,
  emailVerified: true,
}, {
  email: 'sam@yopmail.com',
  password: 'password',
  verificationToken: null,
  emailVerified: true,
}];
